[tools]
python = "3.13"

[settings]
python.uv_venv_auto = true

[env]
_.python.venv = { path = ".venv" }

[tasks.check]
description = "Format & lint the code"
depends = ['format', 'lint']
alias = 'c'

[tasks.format]
description = "Format the code"
run = "uv run ruff format"

[tasks.lint]
description = "Lint the code"
run = "uv run ruff check"

[tasks.hooks]
description = "Install git hooks"
run = "cp hooks/* .git/hooks/"

[tasks.server]
description = "Run server"
run = "uv run -- uvicorn aggregations.webapp.app:app --reload"
alias = 's'

[tasks.worker]
description = "Run worker"
run = "uv run -- python -m aggregations.aggregator.worker"
alias = 'w'

[tasks.pgcli]
description = "Attach pgcli to the running container"
run = "pgcli postgresql://postgres:postgres@localhost:5432"
